server:
  port: 8082

spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: shop-admin
    password: admin




